// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEHSTVOQl5pM8LFEyLLtrVK_rwtJyn8XU',
    appId: '1:643385977347:web:00c398ab3bffd3fb45fc36',
    messagingSenderId: '643385977347',
    projectId: 'onthithpt-f1a9d',
    authDomain: 'onthithpt-f1a9d.firebaseapp.com',
    storageBucket: 'onthithpt-f1a9d.appspot.com',
    measurementId: 'G-57H5V2JLF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYP4CoQ2k7s0uKqzUB1nNeZhWPAHaV4kE',
    appId: '1:643385977347:android:5a9d07046025bc5a45fc36',
    messagingSenderId: '643385977347',
    projectId: 'onthithpt-f1a9d',
    storageBucket: 'onthithpt-f1a9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzVaUsYsuq5cMUIPU0d82qqZqf9Y1KpM8',
    appId: '1:643385977347:ios:52dd915fa662e48f45fc36',
    messagingSenderId: '643385977347',
    projectId: 'onthithpt-f1a9d',
    storageBucket: 'onthithpt-f1a9d.appspot.com',
    iosBundleId: 'com.example.onThiThpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzVaUsYsuq5cMUIPU0d82qqZqf9Y1KpM8',
    appId: '1:643385977347:ios:70d010f871772eb845fc36',
    messagingSenderId: '643385977347',
    projectId: 'onthithpt-f1a9d',
    storageBucket: 'onthithpt-f1a9d.appspot.com',
    iosBundleId: 'com.example.onThiThpt.RunnerTests',
  );
}
